mystr = "Jaydeep is a good boy"
print(len(mystr))
print(mystr[0:21])
print(mystr[0:7:2])
print(mystr.count("o"))
print(mystr.endswith("boy"))
print(mystr.capitalize())
print(mystr.lower())
print(mystr.upper())
print(mystr.replace("is","was"))